// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>

#ifndef MERIDIAN_CPU_H
#define MERIDIAN_CPU_H

#include <Uefi.h>

typedef enum
{
    MERIDIAN_UARCH_UNKNOWN = 0,

    MERIDIAN_UARCH_INTEL_CORE2,
    MERIDIAN_UARCH_INTEL_NEHALEM,
    MERIDIAN_UARCH_INTEL_WESTMERE,
    MERIDIAN_UARCH_INTEL_SANDY_BRIDGE,
    MERIDIAN_UARCH_INTEL_IVY_BRIDGE,
    MERIDIAN_UARCH_INTEL_HASWELL,
    MERIDIAN_UARCH_INTEL_BROADWELL,
    MERIDIAN_UARCH_INTEL_SKYLAKE,
    MERIDIAN_UARCH_INTEL_KABY_LAKE,
    MERIDIAN_UARCH_INTEL_COFFEE_LAKE,
    MERIDIAN_UARCH_INTEL_CANNON_LAKE,
    MERIDIAN_UARCH_INTEL_ICE_LAKE,
    MERIDIAN_UARCH_INTEL_COMET_LAKE,
    MERIDIAN_UARCH_INTEL_ROCKET_LAKE,
    MERIDIAN_UARCH_INTEL_TIGER_LAKE,
    MERIDIAN_UARCH_INTEL_ALDER_LAKE,
    MERIDIAN_UARCH_INTEL_RAPTOR_LAKE,
    MERIDIAN_UARCH_INTEL_METEOR_LAKE,
    MERIDIAN_UARCH_INTEL_UNKNOWN,

    MERIDIAN_UARCH_AMD_K8,
    MERIDIAN_UARCH_AMD_K10,
    MERIDIAN_UARCH_AMD_BULLDOZER,
    MERIDIAN_UARCH_AMD_EXCAVATOR,
    MERIDIAN_UARCH_AMD_ZEN,
    MERIDIAN_UARCH_AMD_ZEN_PLUS,
    MERIDIAN_UARCH_AMD_ZEN2,
    MERIDIAN_UARCH_AMD_ZEN3,
    MERIDIAN_UARCH_AMD_ZEN4,
    MERIDIAN_UARCH_AMD_ZEN5,
    MERIDIAN_UARCH_AMD_UNKNOWN,
} MeridianUarch;

typedef struct
{
    CHAR8 Vendor[13];
    UINT32 Family;
    UINT32 Model;
    UINT32 Stepping;
    MeridianUarch Uarch;
    BOOLEAN IsIntel;
    BOOLEAN IsAmd;

    BOOLEAN HasThermalMsrs;
    BOOLEAN IsHaswell;
    BOOLEAN HasRdrand;
} MeridianCpuInfo;

#include "cpu/intel.h"
#include "cpu/amd.h"

const MeridianCpuInfo *MeridianGetCpuInfo(VOID);

const CHAR8 *MeridianUarchName(MeridianUarch Uarch);

#endif
