// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>

#include "../cpu.h"

#define STEP_ANY 0xFF

#define INTEL_MEROM 0x0F
#define INTEL_PENRYN 0x17

#define INTEL_BLOOMFIELD 0x1A
#define INTEL_LYNNFIELD 0x1E
#define INTEL_CLARKSFIELD 0x1F
#define INTEL_BECKTON 0x2E

#define INTEL_CLARKDALE 0x25
#define INTEL_GULFTOWN 0x2C
#define INTEL_WESTMERE_EX 0x2F

#define INTEL_SANDY_BRIDGE 0x2A
#define INTEL_SANDY_BRIDGE_EP 0x2D

#define INTEL_IVY_BRIDGE 0x3A
#define INTEL_IVY_BRIDGE_EP 0x3E

#define INTEL_HASWELL 0x3C
#define INTEL_HASWELL_EP 0x3F
#define INTEL_HASWELL_ULT 0x45
#define INTEL_HASWELL_GT3 0x46

#define INTEL_BROADWELL 0x3D
#define INTEL_BROADWELL_H 0x47
#define INTEL_BROADWELL_EP 0x4F
#define INTEL_BROADWELL_DE 0x56

#define INTEL_SKYLAKE_MOBILE 0x4E
#define INTEL_SKYLAKE 0x5E
#define INTEL_SKYLAKE_X 0x55

#define INTEL_KBL_CFL_U 0x8E
#define INTEL_KBL_CFL_H 0x9E
#define INTEL_KBL_MAX_STEP 0x09
#define INTEL_CFL_MIN_STEP 0x0A
#define INTEL_AMBER_LAKE_Y 0xBE

#define INTEL_CANNON_LAKE 0x66

#define INTEL_ICE_LAKE_U 0x7E
#define INTEL_ICE_LAKE_Y 0x7D

#define INTEL_COMET_LAKE_S 0xA5
#define INTEL_COMET_LAKE_U 0xA6

#define INTEL_TIGER_LAKE_U 0x8C
#define INTEL_TIGER_LAKE_H 0x8D

#define INTEL_ROCKET_LAKE 0xA7

#define INTEL_ALDER_LAKE_S 0x97
#define INTEL_ALDER_LAKE_P 0x9A

#define INTEL_RAPTOR_LAKE_S 0xB7
#define INTEL_RAPTOR_LAKE_P 0xBA
#define INTEL_RAPTOR_LAKE_B 0xBF

#define INTEL_METEOR_LAKE_M 0xAA
#define INTEL_METEOR_LAKE_S 0xAC

typedef struct
{
    UINT32 Model;
    UINT32 StepMin;
    UINT32 StepMax;
    MeridianUarch Uarch;
} IntelModelEntry;

static const IntelModelEntry IntelF6Table[] = {
    {INTEL_MEROM, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_CORE2},
    {INTEL_PENRYN, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_CORE2},
    {INTEL_BLOOMFIELD, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_NEHALEM},
    {INTEL_LYNNFIELD, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_NEHALEM},
    {INTEL_CLARKSFIELD, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_NEHALEM},
    {INTEL_BECKTON, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_NEHALEM},
    {INTEL_CLARKDALE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_WESTMERE},
    {INTEL_GULFTOWN, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_WESTMERE},
    {INTEL_WESTMERE_EX, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_WESTMERE},
    {INTEL_SANDY_BRIDGE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_SANDY_BRIDGE},
    {INTEL_SANDY_BRIDGE_EP, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_SANDY_BRIDGE},
    {INTEL_IVY_BRIDGE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_IVY_BRIDGE},
    {INTEL_IVY_BRIDGE_EP, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_IVY_BRIDGE},
    {INTEL_HASWELL, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_HASWELL},
    {INTEL_HASWELL_EP, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_HASWELL},
    {INTEL_HASWELL_ULT, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_HASWELL},
    {INTEL_HASWELL_GT3, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_HASWELL},
    {INTEL_BROADWELL, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_BROADWELL},
    {INTEL_BROADWELL_H, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_BROADWELL},
    {INTEL_BROADWELL_EP, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_BROADWELL},
    {INTEL_BROADWELL_DE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_BROADWELL},
    {INTEL_SKYLAKE_MOBILE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_SKYLAKE},
    {INTEL_SKYLAKE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_SKYLAKE},
    {INTEL_SKYLAKE_X, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_SKYLAKE},
    {INTEL_KBL_CFL_U, 0x00, INTEL_KBL_MAX_STEP, MERIDIAN_UARCH_INTEL_KABY_LAKE},
    {INTEL_KBL_CFL_H, 0x00, INTEL_KBL_MAX_STEP, MERIDIAN_UARCH_INTEL_KABY_LAKE},
    {INTEL_KBL_CFL_U, INTEL_CFL_MIN_STEP, STEP_ANY, MERIDIAN_UARCH_INTEL_COFFEE_LAKE},
    {INTEL_KBL_CFL_H, INTEL_CFL_MIN_STEP, STEP_ANY, MERIDIAN_UARCH_INTEL_COFFEE_LAKE},
    {INTEL_AMBER_LAKE_Y, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_COFFEE_LAKE},
    {INTEL_CANNON_LAKE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_CANNON_LAKE},
    {INTEL_ICE_LAKE_Y, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_ICE_LAKE},
    {INTEL_ICE_LAKE_U, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_ICE_LAKE},
    {INTEL_COMET_LAKE_S, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_COMET_LAKE},
    {INTEL_COMET_LAKE_U, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_COMET_LAKE},
    {INTEL_TIGER_LAKE_U, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_TIGER_LAKE},
    {INTEL_TIGER_LAKE_H, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_TIGER_LAKE},
    {INTEL_ROCKET_LAKE, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_ROCKET_LAKE},
    {INTEL_ALDER_LAKE_S, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_ALDER_LAKE},
    {INTEL_ALDER_LAKE_P, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_ALDER_LAKE},
    {INTEL_RAPTOR_LAKE_S, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_RAPTOR_LAKE},
    {INTEL_RAPTOR_LAKE_P, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_RAPTOR_LAKE},
    {INTEL_RAPTOR_LAKE_B, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_RAPTOR_LAKE},
    {INTEL_METEOR_LAKE_M, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_METEOR_LAKE},
    {INTEL_METEOR_LAKE_S, STEP_ANY, STEP_ANY, MERIDIAN_UARCH_INTEL_METEOR_LAKE},
};

MeridianUarch MeridianIntelUarch(UINT32 Family, UINT32 Model, UINT32 Stepping)
{
    UINTN i;

    if (Family != 6)
        return MERIDIAN_UARCH_INTEL_UNKNOWN;

    for (i = 0; i < sizeof(IntelF6Table) / sizeof(IntelF6Table[0]); i++) {
        const IntelModelEntry *E = &IntelF6Table[i];
        if (E->Model != Model)
            continue;
        if (E->StepMin != STEP_ANY && Stepping < E->StepMin)
            continue;
        if (E->StepMax != STEP_ANY && Stepping > E->StepMax)
            continue;
        return E->Uarch;
    }
    return MERIDIAN_UARCH_INTEL_UNKNOWN;
}
