# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>
"""
Conn offline font baker (POC stage).

Bakes the exact glyph set used by the Conn text tier into a C header of
coverage-alpha cells. Letters/digits/punctuation come from Liberation Mono
(the same family the mockup specifies); box-drawing and arrows are drawn
procedurally so the frame tiles seamlessly.

This is the "easy" precursor to the locked end-state (an SDF atlas baked
offline). Same architecture, simpler payload: 8-bit coverage instead of SDF.
Regenerate with:  python3 conn/tools/bake_font.py

Cell metrics mirror render_text() in docs/design/ui-2026/conn_gen.py:
  cw=13.2 (advance), ch=27 (cell height), fs=22, baseline at +19 in-cell.
"""
import os
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 14, 27          # bitmap box (>= 13.2 advance, no clipping)
BASELINE       = 19              # in-cell baseline (matches SVG y+ch-8)
FS             = 22
ADVANCE_X      = 13.2
FONT_REG  = "/usr/share/fonts/liberation/LiberationMono-Regular.ttf"
FONT_BOLD = "/usr/share/fonts/liberation/LiberationMono-Bold.ttf"
OUT = os.path.join(os.path.dirname(__file__), "..", "core", "font_atlas.h")

# Codepoints drawn procedurally (box-drawing + arrows). cp -> draw(d, bold)
def _h(d, _):  # ─
    w = 3 if _ else 2; d.line([(0, CELL_H//2), (CELL_W, CELL_H//2)], fill=255, width=w)
def _v(d, _):  # │
    w = 3 if _ else 2; d.line([(CELL_W//2, 0), (CELL_W//2, CELL_H)], fill=255, width=w)
def _corner(rx, dy):
    def draw(d, b):
        w = 3 if b else 2; cx, cy = CELL_W//2, CELL_H//2
        d.line([(cx, cy), (CELL_W if rx > 0 else 0, cy)], fill=255, width=w)
        d.line([(cx, cy), (cx, CELL_H if dy > 0 else 0)], fill=255, width=w)
    return draw
def _tee(rx):  # ├ / ┤ : full vertical + half horizontal
    def draw(d, b):
        w = 3 if b else 2; cx, cy = CELL_W//2, CELL_H//2
        d.line([(cx, 0), (cx, CELL_H)], fill=255, width=w)
        d.line([(cx, cy), (CELL_W if rx > 0 else 0, cy)], fill=255, width=w)
    return draw
def _arrow(up):
    def draw(d, b):
        cx = CELL_W//2; tip = 5 if up else CELL_H-6; tail = CELL_H-6 if up else 5
        d.line([(cx, tail), (cx, tip)], fill=255, width=2)
        head = -1 if up else 1
        d.line([(cx, tip), (cx-4, tip+4*head)], fill=255, width=2)
        d.line([(cx, tip), (cx+4, tip+4*head)], fill=255, width=2)
    return draw

PROC = {
    0x2500: _h,        0x2502: _v,
    0x250C: _corner( 1,  1), 0x2510: _corner(-1,  1),
    0x2514: _corner( 1, -1), 0x2518: _corner(-1, -1),
    0x251C: _tee( 1),  0x2524: _tee(-1),
    0x2191: _arrow(True), 0x2193: _arrow(False),
}

def glyph_set():
    cps = list(range(0x20, 0x7F))         # printable ASCII
    cps += [0xB7]                          # middot
    cps += list(PROC.keys())
    return cps

def render_cell(cp, font, bold):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    if cp in PROC:
        PROC[cp](d, bold)
    elif cp != 0x20:
        ch = chr(cp)
        adv = font.getlength(ch)
        x = (CELL_W - adv) / 2.0
        d.text((x, BASELINE), ch, font=font, fill=255, anchor="ls")
    return list(img.tobytes())

def main():
    cps = glyph_set()
    reg = ImageFont.truetype(FONT_REG, FS)
    bold = ImageFont.truetype(FONT_BOLD, FS)
    atlas = {0: [], 1: []}  # weight -> [glyph][pixels]
    for cp in cps:
        atlas[0].append(render_cell(cp, reg, False))
        atlas[1].append(render_cell(cp, bold, True))

    n = len(cps)
    L = []
    # REUSE-IgnoreStart -- these are the header of the GENERATED file, not ours
    L.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    L.append("// SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>")
    # REUSE-IgnoreEnd
    L.append("// GENERATED by conn/tools/bake_font.py -- do not edit by hand.")
    L.append("#ifndef CONN_FONT_ATLAS_H")
    L.append("#define CONN_FONT_ATLAS_H")
    L.append(f"#define CONN_CELL_W {CELL_W}")
    L.append(f"#define CONN_CELL_H {CELL_H}")
    L.append(f"#define CONN_BASELINE {BASELINE}")
    L.append(f"#define CONN_ADVANCE_X {ADVANCE_X}")
    L.append(f"#define CONN_GLYPH_COUNT {n}")
    L.append("static const unsigned int conn_glyph_cp[CONN_GLYPH_COUNT] = {")
    L.append("  " + ", ".join(str(c) for c in cps))
    L.append("};")
    L.append("// [weight 0=regular 1=bold][glyph][row-major CELL_H*CELL_W coverage]")
    L.append("static const unsigned char conn_glyph_alpha"
             "[2][CONN_GLYPH_COUNT][CONN_CELL_H*CONN_CELL_W] = {")
    for w in (0, 1):
        L.append("{")
        for gi in range(n):
            data = atlas[w][gi]
            L.append("{" + ",".join(str(v) for v in data) + "},")
        L.append("},")
    L.append("};")
    L.append("#endif")
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"baked {n} glyphs x2 weights -> {os.path.relpath(OUT)} "
          f"({CELL_W}x{CELL_H} cells)")

if __name__ == "__main__":
    main()
