# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>
"""
Conn boot-splash baker.

Authoring is SVG (conn/art/splash/<key>.svg); the firmware never sees SVG or
PNG. Each logo is rasterised OFFLINE with rsvg-convert, its alpha channel taken
as 8-bit coverage, RLE-compressed, and emitted into conn/core/splash_atlas.h as
one mono plane per OS. At runtime ConnLaunchSplash() expands a plane and tints
the coverage with the booting OS's accent colour -- so the source fill colour is
irrelevant; only shape/alpha matter. Sibling of bake_font.py (same Pillow dep,
same generated-header style); RLE is the local coverage-plane scheme (raw
256x256x8 = 512KB is too big for a bootloader uncompressed).

Regenerate with:  python3 conn/tools/bake_splash.py   (or: make -C conn splash)
"""
import os, subprocess, tempfile
from PIL import Image


def compress_rle(raw):
    """Coverage-plane RLE: run marker = runlen+125 (>=128) then the byte;
    literal marker = len-1 (<128) then len bytes. Runs are 3..130 bytes."""
    def flush(buf):
        out = []
        while len(buf) > 128:
            out.append(127); out.extend(buf[:128]); buf = buf[128:]
        if buf:
            out.append(len(buf) - 1); out.extend(buf)
        return out

    comp, back = [], []
    while len(raw) >= 3:
        c = raw[0]
        if raw[1] == c and raw[2] == c:
            n = 3
            while n < 130 and len(raw) > n and raw[n] == c:
                n += 1
            comp.extend(flush(back)); back = []
            comp.append(n + 125); comp.append(c)
            raw = raw[n:]
        else:
            back.append(c); raw = raw[1:]
    back.extend(raw)
    comp.extend(flush(back))
    return comp

SIZE = 256  # square coverage cell (CONN_SPLASH_W == CONN_SPLASH_H)

ART = os.path.join(os.path.dirname(__file__), "..", "art", "splash")
OUT = os.path.join(os.path.dirname(__file__), "..", "core", "splash_atlas.h")

# Order is the runtime index order. Index 0 is the generic fallback. The keys
# are matched (case-insensitive substring of the cleaned entry title) in THIS
# order by ConnLaunchSplash(), so the generic "linux" MUST come last -- else
# "Arch Linux" would match "linux" before "arch". By the same rule "omarchy"
# must precede "arch", which it contains. Unmatched OSes fall back to the
# OSType char map, then to index 0.
KEYS = ["meridian", "cydia", "macos", "windows", "omarchy", "arch",
        "freebsd", "dragonfly", "openbsd", "netbsd", "ghostbsd", "9front", "linux"]


def coverage(key):
    """rsvg-convert <key>.svg -> RGBA PNG -> 8-bit alpha bytes (row-major)."""
    svg = os.path.join(ART, key + ".svg")
    if not os.path.isfile(svg):
        raise SystemExit(f"missing splash art: {svg}")
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        png = tmp.name
    try:
        subprocess.run(
            ["rsvg-convert", "-w", str(SIZE), "-h", str(SIZE), "-o", png, svg],
            check=True)
        img = Image.open(png).convert("RGBA")
        if img.size != (SIZE, SIZE):
            img = img.resize((SIZE, SIZE), Image.LANCZOS)
        return list(img.split()[3].tobytes())  # alpha plane
    finally:
        os.unlink(png)


def main():
    n = len(KEYS)
    comp = [compress_rle(coverage(k)) for k in KEYS]
    raw_total = n * SIZE * SIZE
    comp_total = sum(len(c) for c in comp)

    L = []
    # REUSE-IgnoreStart -- header of the GENERATED file, not ours
    L.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    L.append("// SPDX-FileCopyrightText: 2026 Abdelkader Boudih <oss@seuros.com>")
    # REUSE-IgnoreEnd
    L.append("// GENERATED by conn/tools/bake_splash.py -- do not edit by hand.")
    L.append("#ifndef CONN_SPLASH_ATLAS_H")
    L.append("#define CONN_SPLASH_ATLAS_H")
    L.append(f"#define CONN_SPLASH_W {SIZE}")
    L.append(f"#define CONN_SPLASH_H {SIZE}")
    L.append(f"#define CONN_SPLASH_COUNT {n}")
    L.append("// index 0 == generic fallback; matched by ConnLaunchSplash()")
    L.append("static const char conn_splash_key[CONN_SPLASH_COUNT][16] = {")
    L.append("  " + ", ".join(f"\"{k}\"" for k in KEYS))
    L.append("};")
    L.append("// RLE coverage planes; a plane")
    L.append("// expands to CONN_SPLASH_W*CONN_SPLASH_H bytes of 0..255 coverage.")
    for gi in range(n):
        L.append(f"static const unsigned char conn_splash_rle_{gi}[] = {{"
                 + ",".join(str(v) for v in comp[gi]) + "};")
    L.append("static const unsigned char * const conn_splash_rle[CONN_SPLASH_COUNT] = {")
    L.append("  " + ", ".join(f"conn_splash_rle_{gi}" for gi in range(n)))
    L.append("};")
    L.append("static const unsigned int conn_splash_rle_len[CONN_SPLASH_COUNT] = {")
    L.append("  " + ", ".join(str(len(comp[gi])) for gi in range(n)))
    L.append("};")
    L.append("#endif")
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"baked {n} splash logos -> {os.path.relpath(OUT)} ({SIZE}x{SIZE}); "
          f"RLE {comp_total} of {raw_total} bytes "
          f"({100.0*comp_total/raw_total:.1f}%)")


if __name__ == "__main__":
    main()
